BTC = "BTCUSDT"

ASSETS = [
"ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","ADAUSDT",
"AVAXUSDT","DOGEUSDT","DOTUSDT","MATICUSDT","LINKUSDT",
"ATOMUSDT","NEARUSDT","APTUSDT","ARBUSDT","OPUSDT",
"INJUSDT","SEIUSDT","SUIUSDT","RUNEUSDT","KASUSDT",
"AAVEUSDT","UNIUSDT","ICPUSDT","FILUSDT","TIAUSDT",
"PYTHUSDT","JUPUSDT","BONKUSDT","STXUSDT","ORDIUSDT",
"WLDUSDT","IMXUSDT","FLOWUSDT","EGLDUSDT","KAVAUSDT",
"ZILUSDT","CHZUSDT","ENSUSDT","DYDXUSDT","SANDUSDT",
"MANAUSDT","AXSUSDT","FTMUSDT","GRTUSDT","PEPEUSDT",
"SHIBUSDT","TRXUSDT","LDOUSDT","RNDRUSDT","NEOUSDT"
]
